import React from 'react'

export default function Overflow() {
  return (
    <div className='w-[100vw] h-[3  00px] overflow-auto'>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit, dolor! Distinctio repudiandae tenetur corporis ex dicta qui odio sed ab voluptatibus doloribus? Modi facere qui vero accusamus nobis dolorem aut.
        Nam quis porro ipsa facilis fugiat id ipsam adipisci, sunt excepturi similique nostrum doloremque. Aut necessitatibus, sed, laborum ab adipisci fugiat ex eaque facere, nulla delectus porro omnis similique blanditiis.
        Et eligendi sint dolores dicta optio, quis ipsam laboriosam amet nemo exercitationem nisi vitae voluptatibus mollitia corrupti facere sit vero minus. Sed facere nisi culpa assumenda! Asperiores, assumenda tempora? Quos?
        Sint eum dolores cupiditate veritatis itaque, voluptas ullam perferendis assumenda eveniet est sit asperiores odit? Doloremque sed quisquam exercitationem sapiente harum consequuntur itaque, quibusdam magni cum veritatis expedita voluptates nisi.
        Repudiandae blanditiis omnis mollitia animi. In voluptates eveniet consectetur placeat voluptatibus nisi dolores possimus ea minus quos repellendus cum, itaque beatae, facere maiores numquam doloremque debitis optio culpa distinctio porro!
        Libero fugiat nostrum sapiente optio ea maxime! Accusantium, cum. Incidunt saepe animi rerum eius porro ab repellat ad quidem magnam esse, quam odit unde recusandae! Vel omnis voluptate illo totam?
        Odit at repellat impedit beatae perferendis deserunt pariatur voluptatum neque quis tenetur similique dolore modi ab explicabo tempore minima nesciunt doloremque, magni ad nobis error dignissimos debitis nemo? Laborum, obcaecati.
        Quisquam repudiandae obcaecati doloremque similique explicabo, commodi odit non quidem porro nihil corrupti, quasi soluta veniam harum. Maiores, cumque praesentium voluptatibus expedita natus placeat dignissimos, assumenda consequuntur, cupiditate eveniet dolorem!
        Aspernatur voluptates dolor doloribus reprehenderit commodi sed molestias, cum cupiditate nemo, sequi facilis! Deleniti, placeat, dicta recusandae vitae aperiam minima iusto assumenda veritatis esse, velit ea. Placeat corporis dolore vitae.
        Aliquid, perspiciatis. Ab, quasi at commodi totam voluptatum illum, odio eaque ullam voluptate id doloremque? Commodi hic totam sed dolore animi? Quo totam nemo ipsum aspernatur voluptatem ab debitis esse.
        Numquam accusamus error ipsam incidunt, aliquid quisquam reprehenderit vero esse illum natus impedit sunt maxime voluptatum explicabo minima magnam ad odit saepe minus vel ullam! Blanditiis soluta a ex non.
        Reprehenderit illum asperiores nihil quaerat facilis corrupti fugit tenetur a voluptate. Vero expedita quos alias qui a veritatis tempora cupiditate culpa, inventore magnam obcaecati atque commodi? Nisi explicabo ad odio.
        Mollitia unde rerum commodi facere quidem quam delectus blanditiis ipsam doloremque? Animi obcaecati vero, voluptate aliquam sed deleniti nobis suscipit, dignissimos cumque, saepe excepturi! Temporibus quam non neque repudiandae fuga.
        Numquam omnis nisi sed aut fugiat consectetur error adipisci veniam eveniet reprehenderit eius ab, officiis tempora, placeat, dolores officia deleniti molestias repellat hic odit maiores. In voluptas eos voluptatibus asperiores.
        Accusantium, alias nobis. Animi libero, commodi delectus natus ducimus beatae sed temporibus ullam totam excepturi tempore! Nemo, aliquid sapiente accusantium maiores voluptate maxime temporibus, quia, nobis facere minus architecto fugit?
        Aperiam et corporis minima aliquid sunt voluptatibus blanditiis assumenda repellat. Dolorem, nam vero, doloremque numquam suscipit error illo incidunt voluptatem amet nesciunt asperiores dolore possimus, veniam architecto cupiditate rerum iste?
        At excepturi sint totam error est eius aut quisquam illo in dolor ipsum sed reiciendis, laboriosam earum facilis velit unde molestiae temporibus iste ipsam aperiam ullam ratione eligendi. Error, pariatur?
        Unde obcaecati fuga accusamus in ratione omnis quibusdam dolore nihil illum vitae, dignissimos minima itaque, quas, sit ipsum placeat explicabo voluptas dolorum praesentium est tenetur rem architecto? Sunt, tempora quam.
        Repudiandae ipsum assumenda eos adipisci harum voluptatum modi similique temporibus! Sapiente beatae saepe fugiat commodi ipsam eum distinctio sit consequuntur dignissimos dicta? Delectus dolorum velit provident facilis omnis numquam voluptas?
        Asperiores recusandae consequatur modi sint id earum aliquam soluta architecto repudiandae, nam molestias. Unde aliquam consequatur aperiam dolorem neque, reiciendis quas quae aliquid, et officiis incidunt facere tenetur expedita optio.
        Quo dolor iste ea quidem vitae sit? Unde velit tempora ipsa tenetur delectus non consequuntur nihil. Rem tempore, impedit assumenda, excepturi iure ipsa itaque explicabo ad necessitatibus dolorum, tenetur laudantium.
        Sunt cumque quos sit tempora impedit, cupiditate velit nostrum possimus hic fugiat at quae, magni mollitia harum maiores, fugit sequi ipsa autem quasi voluptatibus rerum consectetur accusantium. Possimus, dignissimos qui.
        Minus incidunt, maxime fugit eius cum aperiam nemo quos in distinctio velit enim? Eius repellat nam doloremque possimus et nulla molestias. Incidunt ut nam, ex amet eum error voluptates ducimus?
        Ut accusamus assumenda atque suscipit itaque fugiat ex reprehenderit rerum excepturi totam doloremque sit nobis at expedita quidem quaerat molestias, nemo consectetur numquam nisi vitae dolor? Mollitia neque nobis error.
        Non libero modi ea, quas itaque ducimus sunt? Repudiandae nesciunt maxime dolorum rerum libero veniam quaerat ducimus voluptatem sed est, et quod fuga totam harum. Quos molestias odit repellat id!
        Repudiandae sit consequatur architecto aut unde? Dicta vel expedita architecto reiciendis tempora, explicabo incidunt numquam ipsam vero est! Fugit quos libero deserunt qui eligendi eos natus vel sequi maxime in.
        Aut, aperiam ipsam quidem cumque commodi voluptas. Autem recusandae praesentium est voluptatibus eum dignissimos quibusdam eos, similique at maiores nam hic quod? Nihil error aspernatur facilis, illum nostrum sapiente rem.
        Cupiditate, labore inventore. Architecto dolores error deleniti? Officia recusandae rem amet pariatur tempore debitis quae cumque. Exercitationem totam possimus soluta accusamus laborum consequatur, quisquam distinctio placeat labore amet aliquam! Exercitationem.
        Quidem magnam est eum illum veritatis nostrum molestiae autem magni saepe consequuntur quae earum natus, quaerat minima numquam vitae, pariatur itaque tenetur sed nulla facilis totam. Commodi sequi tempore consequatur.
        Provident sapiente, ipsam vero sint quas iusto amet vel omnis perspiciatis rem dolorum aspernatur officia nesciunt, iure porro quaerat dolores? Expedita saepe necessitatibus qui, fugit perferendis totam. Libero, ipsam architecto?
        Ipsam, vitae voluptate voluptatibus laborum perspiciatis natus? Doloremque explicabo exercitationem fuga eveniet delectus consequatur voluptates rem, aliquam laborum corrupti similique rerum dignissimos deserunt aspernatur qui voluptatem assumenda quisquam laudantium ipsa!
        Amet beatae commodi quos unde similique, ratione hic eius suscipit itaque modi obcaecati alias ea, tempore illum animi distinctio sapiente repellendus quidem illo culpa vel cumque perspiciatis? Rem, quidem dignissimos.
        Quia enim cum voluptate harum, ut recusandae adipisci iusto. Laboriosam exercitationem, non doloribus deleniti quo earum voluptas laborum sunt repellat expedita, architecto inventore dolor! Corporis accusamus ea libero laborum deleniti.
        Minima quis minus iste. Porro corrupti maxime, atque, eligendi modi, repellat nostrum nobis a et odio vel voluptatibus dolores optio quae quis? Consectetur voluptatibus natus molestias. Adipisci ab soluta officiis.
        Cum aut eum distinctio veniam beatae optio ea nostrum soluta cupiditate fuga, laboriosam consequatur fugiat debitis culpa vel sunt rerum ad numquam, quos quod animi, minima tempora amet. Debitis, vel.
        Dignissimos porro reiciendis quo ratione corrupti tenetur totam magnam dolore ad obcaecati hic, enim ipsam, quod et sed facere magni consequatur eos nostrum? Necessitatibus, modi natus? Fugit omnis et eveniet.
        Corporis autem earum quas, provident voluptatem eos fugiat a sint illo rerum voluptatum dolor. Reiciendis magni cum odit ipsa quisquam iste minus quidem perspiciatis, exercitationem, earum laborum dicta facilis ipsum.
        Recusandae nam, nostrum quos molestias alias voluptates cupiditate blanditiis, vitae et dolorum optio laboriosam delectus inventore odio ducimus iste nesciunt eveniet dignissimos tempora natus. Earum, fuga. Soluta fuga pariatur itaque.
        Neque ullam, error natus quis tempore, magnam facere laborum repellat necessitatibus hic blanditiis iste incidunt dolores nesciunt vel ex veritatis! Minus deserunt debitis aspernatur velit doloribus illo dolore dolor reprehenderit.
        Quae dignissimos necessitatibus facere? Suscipit delectus non blanditiis vitae, distinctio inventore atque deleniti, adipisci cum necessitatibus architecto. Ad error, iste laboriosam beatae illo, libero vero dignissimos vel nam sint at!
        Sunt expedita magni quisquam, alias numquam nesciunt animi excepturi vero consequatur temporibus dolorem nam natus voluptatum molestiae laboriosam at illo nostrum minus recusandae necessitatibus facere? Eius commodi aliquid dolorem reiciendis.
        Doloremque nostrum, necessitatibus ut itaque omnis delectus rem numquam assumenda, veritatis repudiandae, harum similique aperiam. Iusto debitis labore, ad, adipisci amet optio, inventore magnam minima eos in sint laudantium aperiam!
        Optio eligendi modi ut rem explicabo nisi mollitia nemo assumenda illum iste quo voluptatem, quas obcaecati accusamus vel possimus numquam, dolor quidem unde exercitationem odit dolorum. Iure alias veniam qui.
        Exercitationem debitis saepe velit natus blanditiis perspiciatis porro, minima harum quae adipisci veniam repellat dolores aliquid non numquam amet doloremque expedita animi minus repudiandae id omnis deserunt odio. Commodi, ullam.
        Repellat sit praesentium quo, quia dicta sapiente eius ab amet libero illum dolorem sequi, optio qui vel. Mollitia vero ipsam expedita dolorum, voluptatem quasi beatae tenetur, hic nulla aliquid tempore?
        Nisi molestiae aspernatur nostrum! Corrupti architecto ipsam dignissimos! Veniam inventore quasi quisquam dignissimos voluptas iusto aut, commodi temporibus saepe repudiandae repellendus consequuntur possimus magni quis beatae eligendi eveniet dolore laborum.
        At ipsam, esse animi iste cum debitis nam reiciendis a est optio veritatis fugiat, officiis nihil velit laborum porro recusandae ipsa quasi! Officia, maxime sint eveniet perferendis maiores sit repellat.
        Voluptates aut blanditiis accusantium ipsa ipsum rerum, corporis suscipit vero temporibus tenetur illo eos debitis ducimus voluptas ab iure molestias at assumenda dolorem accusamus unde recusandae? Dolorem, ipsum. Facilis, in!
        Vero dolore, nisi eligendi voluptate veniam commodi alias inventore officia consectetur quisquam unde beatae. Possimus ratione repellendus et non, cupiditate, enim deleniti, itaque commodi voluptas quasi illum nam neque veniam.
        Vel illo officia id hic officiis numquam rem perferendis! Quibusdam laboriosam odit animi totam voluptas culpa autem incidunt praesentium veritatis consequuntur esse magni possimus assumenda exercitationem iste at, suscipit labore.
    </div>
  )
}
